server:
    port: 4001
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:4000/eureka
    instance:
        instance-id: consumer #此实例注册到eureka服务端得唯一得实例id
        prefer-ip-address: true #是否显示ip地址
        lease-renewal-interval-in-seconds: 10 #Eureka服务器在接收到实例得最后一次发出得心跳后，需要等待多久才可以将此实例删除，默认90秒
spring:
    application:
        name: consumer