server:
    port: 4011
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:4000/eureka
    instance:
        instance-id: gateway #此实例注册到eureka服务端得唯一得实例id
        prefer-ip-address: true #是否显示ip地址
        lease-renewal-interval-in-seconds: 10 #eureka客户需要多长时间发送心跳给eureka服务器，表明它仍 然活着,默认为30 秒 (与下面配置的单位都是秒)
        lease-expiration-duration-in-seconds: 30 #Eureka服务器在接收到实例得最后一次发出得心跳后，需要等待多久才可以将此实例删除，默认90秒
spring:
    application:
        name: gateway
    cloud:
        gateway:
            routes:
                - id: gateway_route_path # 路由的id,没有规定规则但要求唯一,建议配合服务名
                #匹配后提供服务的路由地址
                  uri: http://localhost:4002/index/
                  predicates:
                      - Path=/index/** # 断言，路径相匹配的进行路由
                - id: gateway_route_name # 路由的id,没有规定规则但要求唯一,建议配合服务名
                  #使用服务名转发
                  uri: lb://ribbon
                  predicates:
                      - Path=/index/sleep # 断言，路径相匹配的进行路由