server:
    port: 4000
eureka:
    server:
        enable-self-preservation: false #关闭自我保护机制
        eviction-interval-timer-in-ms: 4000 #设置清理间隔(单位:毫秒 默认是60*1000)
    instance:
        hostname: localhost
    client:
#        service-url:
##            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
        ###是否将自己注册到Eureka服务中,因为该应用本身就是注册中心，不需要再注册自己（集群的时候为true）
        register-with-eureka: false
        ###是否从Eureka中获取注册信息,因为自己为注册中心,不会在该应用中的检索服务信息
        fetch-registry: false
logging:
    file: log/eureka.log